version: '3'
services:
  my_db:
    environment: [MYSQL_ALLOW_EMPTY_PASSWORD=yes]
    expose: [3306]
    image: mysql:latest
    networks: [db_net]
    ports: ['3306:3306']
networks:
  db_net: {driver: bridge}