# This file is meant to be ran after:
# 1. Spawning the docker-compose.yml in the main ESM directory
# 2. De-spawning the esm_ui
# Only then we can spawn this volume-mounted instance to develop or to play around with the UI internals.
 
version: '3'
services:
  esm_ui:
    container_name: esm_ui
    hostname: esm_ui
    # depends_on:
    #   - esm
    # image: ademord/esmweb:latest
    
    # environment:
    #   - DEBUG=true
    #   - SECRET_KEY=not secure only use for development
    #   - ET_ESM_API=http://esm:8080
    # networks:
    #   - elastest
    # # ports:
    #   - 8000:8000
    # expose:
    #   - 8000
    
    build: .
    # command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=true
      - SECRET_KEY=not secure only use for development
      - ET_ESM_API=http://esm:37005
    volumes:
      - .:/usr/src/app
    networks:
      - elastest
    ports:
      - 8000:8000
    expose:
      - 8000
    
networks:
  elastest:
    external:
      name: esm_elastest
